import Head from "next/head";
import Navbar from "./Navbar";

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>My portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="fixed top-0 w-full">
        <Navbar />
      </div>

      {children}
      <footer className="flex bg-black text-white justify-center items-center h-40 mt-10">
        <div className="flex flex-col ">
          <div className="flex justify-center items-center">
            <div>LinkedIn</div>
            <dir>Github</dir>
          </div>
          <div>Copyright - 2021 Chih Yu Lee, All Right Reserved</div>
        </div>
      </footer>
    </div>
  );
};

export default Layout;
